"""Marketing Director — wraps the brief for marketing-studio one-link runs.

Triggered when ``brief.mode == "marketing"``. Pre-fills three high-converting
hook archetypes (problem/solution, social proof, demo-to-click) and a 3-format
mix (vertical reel, square feed, horizontal display) so the downstream
Strategist + Creative Director don't have to invent these from scratch.

Returns a state delta (NOT a replacement). The orchestrator merges this into
the run state before Strategist runs.
"""

from __future__ import annotations

from typing import Any

# Three hook archetypes proven on DTC ads. Concrete copy gets generated by
# the Copywriter downstream — these are *angles* the strategist must address.
_MARKETING_HOOKS: tuple[str, ...] = (
    "problem-solution: surface the pain, then the product as relief",
    "social-proof: lead with a real customer quote or rating",
    "demo-to-click: show the product in action with a single CTA",
)

_MARKETING_FORMAT_MIX: tuple[str, ...] = ("reel", "square", "banner")


async def forward(state: dict[str, Any], _runtime: Any) -> dict[str, Any]:
    """Augment the brief with marketing defaults if mode == "marketing"."""

    brief = dict(state.get("brief") or {})
    if brief.get("mode") != "marketing":
        return state

    # Don't clobber explicit hooks the user already supplied.
    existing_hooks = list(brief.get("hooks") or [])
    if not existing_hooks:
        brief["hooks"] = list(_MARKETING_HOOKS)

    return {
        **state,
        "brief": brief,
        # `format_mix` is normally produced by the Creative Director; we seed
        # it so the orchestrator always emits the 3-format spread the
        # one-link UX expects.
        "format_mix": list(_MARKETING_FORMAT_MIX),
    }


MARKETING_HOOKS = _MARKETING_HOOKS
MARKETING_FORMAT_MIX = _MARKETING_FORMAT_MIX

__all__ = ["forward", "MARKETING_HOOKS", "MARKETING_FORMAT_MIX"]
